[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[tools]
"rust" = [
  { version = "stable", components = "rust-src,llvm-tools,rust-analyzer" },
  { version = "nightly", components = "rust-src,llvm-tools,rust-analyzer" },
]
"go" = "latest"
"python" = "latest"
"node" = "22"
"bun" = "latest"
"uv" = "latest"
"gemini-cli" = "latest"
"claude-code" = "latest"
"pnpm" = "latest"
"typst" = "latest"
"jq" = "latest"
"zoxide" = "latest"
"neovim" = "latest"
"dust" = "latest"
"has" = "latest"
"tree-sitter" = "latest"
"jj" = "latest"
"gh" = "latest"
"chezmoi" = "latest"
"cargo:eza" = "latest"
"npm:@typescript/native-preview" = "latest"
"ghq" = "latest"
"yazi" = "latest"
"fzf" = "latest"
"fastfetch" = "latest"

[hooks]
postinstall = "npx corepack enable"

[tasks."brew-install"]
run = "Brew bundle"
