[user]
name = "crcrworks"
email = "42961885+crcrworks@users.noreply.github.com"

[ui]
default-command = "log"

[remotes.origin]
auto-track-bookmarks = "glob:*"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | remote_bookmarks()"
